config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  devise_for :users
=======
  devise_for :models
>>>>>>> 47d557b2170b92ce5a903d7838b62e81ca116168

root 'todos#index'

resources :todos do
collection do
  get '/:id' =>'todos#change', as: :change
  post '/showDone' =>'todos#showDone',as: :showDone
  post '/showUndone' =>'todos#showUndone',as: :showUndone
end
end

end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
<<<<<<< HEAD
   # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
=======
 protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
>>>>>>> 47d557b2170b92ce5a903d7838b62e81ca116168
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
before_action:find_todo,:only=>[:edit,:destroy,:update,:change]

	def index
	@todo=Todo.new
	@todos=Todo.all
	end

	def change
	if @todo.status==true
	@todo.status=false
	elsif @todo.status==false
	@todo.status=true
	end
	if @todo.save
	redirect_to root_path
	end
	end

	def showDone
	@todos = Todo.where(status: true)
	end

	def showUndone
	@todos = Todo.where(status: false)
	end
	
	
	
	
	def create
	@todo=Todo.new(todo_params)
	@todo.update_attribute(:status,false)
	if @todo.save
	redirect_to root_path
	else
		render:new

	end
	end

	def edit
	end

	def destroy
	@todo.destroy
	redirect_to root_path
	end


	def update
		
		if @todo.update(todo_params)
			redirect_to root_path
		else
			render:edit
		end
	end
	
	
	
	private
	def  find_todo
		@todo=Todo.find(params[:id])
	end
	def todo_params
		params.require(:todo).permit(:eventName,:status)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist1App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<<<<<<< HEAD
<% if user_signed_in? %>
Hello,<%=current_user.name%>!
<%= link_to "Sign out", destroy_user_session_path,method:'delete' %>
<% else %>
<%= link_to "Sign up", new_user_registration_path %>
<%= link_to "Sign in", new_user_session_path %>
<% end %>
=======
<header >
<% if model_signed_in?%>
<div >
你好,<%=current_model.name%>
</div>
<div >
<%= link_to "sign out",destroy_model_session_path,method:"delete"%>
</div>
<%else%>
<div >
<%= link_to "sign up",new_model_registration_path%>
<%= link_to "sign in",new_model_session_path%>
</div>
<%end%>

</header>
>>>>>>> 47d557b2170b92ce5a903d7838b62e81ca116168
<%= yield %>

</body>
</html>

app/views/models/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/todos/edit.html.erb
<%= form_for @todo do|f|%>
	<%=f.text_field :eventName%>
	<%=f.submit%>
	<%end%>

app/views/todos/index.html.erb
<h2>Todo List</h2>

新增事項:<%= form_for @todo do|f|%>
	<%=f.text_field :eventName%>
	<%=f.submit%>
	<%end%>
<div>
<%= button_to "All",todos_path,method:"get"%>
<%= button_to "完成", showDone_todos_path,method:"post"%>
<%= button_to "尚未完成",showUndone_todos_path,method:"post"%>
</div>

<ul>
<%@todos.each do|todo|%>
<li>
<% if todo.status==false%>
<%=todo.eventName%>
<%= button_to "尚未完成",change_todos_path(todo), method:"get"%>
<%end%>
<% if todo.status==true%>
<%=todo.eventName%>
<%= button_to "完成",change_todos_path(todo), method:"get"%>
<%end%>
<%=link_to "編輯",edit_todo_path(todo)%>
<%=link_to "刪除",todo_path(todo),method:"delete"%>

</li>
<%end%>
</ul>

app/views/todos/showDone.html.erb
<h2>Todo List</h2>

新增事項:<%= form_for Todo.new do|f|%>
	<%=f.text_field :eventName%>
	<%=f.submit%>
	<%end%>
<div>
<%= button_to "All",todos_path,method:"get"%>
<%= button_to "完成", showDone_todos_path,method:"post"%>
<%= button_to "尚未完成",showUndone_todos_path,method:"post"%>
</div>

<ul>
<%@todos.each do|todo|%>
<li>
<% if todo.status==false%>
<%=todo.eventName%>
<%= button_to "尚未完成",change_todos_path(todo), method:"get"%>
<%end%>
<% if todo.status==true%>
<%=todo.eventName%>
<%= button_to "完成",change_todos_path(todo), method:"get"%>
<%end%>
<%=link_to "編輯",edit_todo_path(todo)%>
<%=link_to "刪除",todo_path(todo),method:"delete"%>

</li>
<%end%>
</ul>

app/views/todos/showUndone.html.erb
<h2>Todo List</h2>

新增事項:<%= form_for Todo.new do|f|%>
	<%=f.text_field :eventName%>
	<%=f.submit%>
	<%end%>
<div>
<%= button_to "All",todos_path,method:"get"%>
<%= button_to "完成", showDone_todos_path,method:"post"%>
<%= button_to "尚未完成",showUndone_todos_path,method:"post"%>
</div>

<ul>
<%@todos.each do|todo|%>
<li>
<% if todo.status==false%>
<%=todo.eventName%>
<%= button_to "尚未完成",change_todos_path(todo), method:"get"%>
<%end%>
<% if todo.status==true%>
<%=todo.eventName%>
<%= button_to "完成",change_todos_path(todo), method:"get"%>
<%end%>
<%=link_to "編輯",edit_todo_path(todo)%>
<%=link_to "刪除",todo_path(todo),method:"delete"%>

</li>
<%end%>
</ul>